package assignment2;

public class assignment2 {
	String spaces(int row)    //function for spaces
	{
		int i;
		String s="";       
		for(i=5;i>row;i--){
	        s=s+" ";
		}
		return s;             
	}
	
	String number(int row)     //function for numbers
	{
		int j=0;
		String num="";
			for(j=1;j<=row;j++){
			num=num+j;            
			}
		return num;
	}
	String[] printwholepyramid(int n){         //whole pattern is generated by concatinating spaces and number strings
	String result[]=new String[n];
	int i;
	for(i=1;i<=n;i++){ 
	String temp1=spaces(n-(i-1));
	String temp2=number(n-(i-1));
	result[i-1]=temp1+temp2;
	}
	return result;
	}

}
